# fly.toml app configuration file generated for pocgrafana on 2024-06-07T11:36:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocgrafana'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
